version: "3.3"
services:
  web:
      image: php:8.2-apache
      restart: always
      ports:
        - "8080:80"
      volumes:
        - ./:/var/www/html
      networks:
        - db-sql
      depends_on:
        - db
      container_name: php_native_app
      command: bash -c "docker-php-ext-install mysqli pdo pdo_mysql && apache2-foreground"
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3301:3306"
    expose:
      - "3301"
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - db-sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8881:80"
    expose:
      - "8881"
    links:
      - "db:db"
    networks:
      - db-sql

volumes:
  my-db:


networks:
  db-sql:
    driver: bridge
